# Sample .travis.yml for R projects.
# Taken from my fork of Craig Citro's r-travis
#
# See https://github.com/eddelbuettel/r-travis/
# and https://github.com/craigcitro/r-travis
#
# See README.md for instructions.

language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget r-cran-rcpp r-cran-runit r-cran-inline r-cran-pinp

script: 
  - ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change# Sample .travis.yml for R projects.
# Taken from my fork of Craig Citro's r-travis
#
# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) r-cran-pinp
  - sudo add-apt-repository -y ppa:edd/misc
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-runit r-cran-inline r-cran-pinp

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

#after_success:
#  - ./run.sh coverage
   
notifications:
  email:
    on_success: change
    on_failure: change
