---
title: |
   \pkg{RcppClassic}: Deprecated Rcpp API

# Use letters for affiliations
author:
  - name: Dirk Eddelbuettel
    affiliation: a
  - name: Romain Fran\c{c}ois
    affiliation: b
address:
  - code: a
    address: \url{http://dirk.eddelbuettel.com}
  - code: b
    address: \url{https://romain.rbind.io/}

# For footer text
lead_author_surname: Eddelbuettel and Fran\c{c}ois

# Place DOI URL or CRAN Package URL here
doi: "https://cran.r-project.org/package=RcppClassic"

# Abstract
abstract: |
  This vignette describes how to use the \pkg{RcppClassic} package. It has 
  long been deprecated and superceded by the more powerful \pkg{Rcpp} package.
  All new \proglang{R} packages should use the \pkg{Rcpp} package instead.

# One or more keywords
keywords:
  - R
  - packages
  - Rcpp
  - API
  - Deprecation

# Customize footer, eg by referencing the vignette
footer_contents: "RcppClassic Vignette"

# Skip the final PNAS-style break
skip_final_break: true

# Our style
output: pinp::pinp

# Local additiona of a few definitions we use
header-includes:
  \newcommand{\proglang}[1]{\textsf{#1}}
  \newcommand{\pkg}[1]{\textbf{#1}}

# Vignette
vignette: >
  %\VignetteIndexEntry{RcppClassic: Deprecated Rcpp API}
  %\VignetteKeywords{R,Rcpp,API}
  %\VignettePackage{RcppClassic}
  %\VignetteEngine{knitr::rmarkdown}

# We include the generated .bbl file directly to not require a bib file
include-after: |
  \begin{thebibliography}{3}
  \newcommand{\enquote}[1]{``#1''}
  \providecommand{\natexlab}[1]{#1}
  \providecommand{\url}[1]{\texttt{#1}}
  \providecommand{\urlprefix}{URL }
  \expandafter\ifx\csname urlstyle\endcsname\relax
    \providecommand{\doi}[1]{doi:\discretionary{}{}{}#1}\else
    \providecommand{\doi}{doi:\discretionary{}{}{}\begingroup
    \urlstyle{rm}\Url}\fi
  \providecommand{\eprint}[2][]{\url{#2}}
  
  \bibitem[{Eddelbuettel(2013)}]{Eddelbuettel:2013:Rcpp}
  Eddelbuettel D (2013).
  \newblock \emph{Seamless R and C++ Integration with Rcpp}.
  \newblock Use R! Springer, New York.
  \newblock ISBN 978-1-4614-6867-7.
  
  \bibitem[{Eddelbuettel and Balamuta(2017)}]{PeerJ:Rcpp}
  Eddelbuettel D, Balamuta JJ (2017).
  \newblock \enquote{Extending R with C++: A Brief Introduction to Rcpp.}
  \newblock \emph{PeerJ Preprints}, \textbf{5}.
  \newblock \urlprefix\url{10.7287/peerj.preprints.3188v1/}.
  
  \bibitem[{Eddelbuettel \emph{et~al.}(2017)Eddelbuettel, Fran\c{c}ois, Allaire,
    Ushey, Kou, Russel, Chambers, and Bates}]{CRAN:Rcpp}
  Eddelbuettel D, Fran\c{c}ois R, Allaire J, Ushey K, Kou Q, Russel N, Chambers
    J, Bates D (2017).
  \newblock \emph{{Rcpp}: Seamless {R} and {C++} Integration}.
  \newblock R package version 0.12.12,
  \urlprefix\url{http://CRAN.R-Project.org/package=Rcpp}.

  \end{thebibliography}

---

\noindent This document presents the \pkg{RcppClassic} package. This
package has been factored out of \pkg{Rcpp}
\citep{CRAN:Rcpp,Eddelbuettel:2013:Rcpp,CRAN:Rcpp,PeerJ:Rcpp} and only
contains code that is considered deprecated.

This package is released for the sole purpose of allowing package authors
that are still using the classic \pkg{Rcpp} API to keep
their package buildable. This document explains the changes needed in
a package to use both the current and classic \pkg{Rcpp} APIs.

# If you must use RcppClassic {.unnumbered}

A few changes are needed in packages that want to use the classic \pkg{Rcpp}
API that is contained in \pkg{RcppClassic}. A sample package called
\pkg{RcppClassicExample} is on CRAN and can be used as a template.

## The `DESCRIPTION` file

The client package must declare that it depends on both \pkg{Rcpp} and \pkg{RcppClassic}
in the Imports field and the LinkingTo field, so it must contain this:

```sh
Imports: RcppClassic, Rcpp
LinkingTo: RcppClassic, Rcpp
```

## The `NAMESPACE` file

The client package should import both \pkg{Rcpp} and \pkg{RcppClassic}:

```{r namespace, eval=FALSE}
importFrom(Rcpp, evalCpp)
import(RcppClassic)
```

## The `Makevars` file

The `Makevars` file must be updated so that user libraries for both \pkg{Rcpp}
and \pkg{RcppClassic} are used.  For \pkg{Rcpp} 0.11.0 we used

```sh
## This can be placed on one or two lines too
PKG_LIBS = \
  `$(R_HOME)/bin/Rscript -e \
     "Rcpp:::LdFlags()"` \
  `$(R_HOME)/bin/Rscript -e \
     "RcppClassic:::LdFlags()"`
```

but starting with \pkg{Rcpp} version 0.11.0, the result of \verb|Rcpp:::LdFlags()| is
an empty string as Rcpp no longer provides a user-library. The above then
reduces to

```sh
## This can be placed on one lines
PKG_LIBS = `$(R_HOME)/bin/Rscript -e \
   "RcppClassic:::LdFlags()"`
```

which finds the required `RcppClassic` library.


## The `Makevars.win` files

The `Makevars.win` must also be updated for the same reason, and in
similar way.  Use `${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe` instead of
`$(R_HOME)/bin/Rscript` to reflect both the bi-architecture nature of
Windows builds and the differently names `Rscript` executable.


## Include `RcppClassic.h` instead of `Rcpp.h`

Finally, all instances of this line :

```c
#include <Rcpp.h>
```

need to be replaced by:

```c
#include <RcppClassic.h>
```


# You should not use RcppClassic {.unnumbered}

The previous section discusses the set of changes required to update a
package so that it uses the classic API from \pkg{RcppClassic} since it has
been removed from \pkg{Rcpp}.

We do, however, recommend that package authors stop using the classic API.
Iy has been more than superseded by the current \pkg{Rcpp} API in terms of
performance, design, maintainance, and ease of use.

